# Generated by Django 4.2.15 on 2024-08-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='título', max_length=100)),
                ('description', models.TextField(db_column='descrição', max_length=1000)),
                ('author', models.CharField(db_column='autor', max_length=100)),
                ('year', models.IntegerField(db_column='ano', default=2000)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'book',
            },
        ),
    ]
